{% set name = "molPX" %}
{% set version = "0.16b3" %}
{% set sha256 = "2f340ace73cdc9e6ba80e32c77e10a114911e1aa9638ef0a2d909a10655851a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - nglview >=1
    - pyemma
    - ipympl
    - scikit-learn
    - notebook

test:
  imports:
    - molpx
about:
  home: https://github.com/markovmodel/molPX
  license: LGPL v3+
  license_file: LICENSE.txt
  summary: "molPX: Molecular Projection Explorer"
  doc_url: https://molpx.readthedocs.io/en/latest/
  dev_url: https://github.com/markovmodel/molPX

extra:
  recipe-maintainers:
    - gph82
    - marscher
