{% set name = "molPX" %}
{% set version = "0.1.5" %}
{% set sha256 = "96d3949580bfcba5debbedafafe17f4def88f93dedf826bf8ba34d6d37eb2344" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - nglview >=0.6.2.3
    - pyemma
    - scikit-learn
    - notebook

test:
  imports:
    - molpx
about:
  home: https://github.com/markovmodel/molPX
  license: LGPL v3+
  # TODO: include in next release
  #license_file: LICENSE.txt
  summary: "molPX: Molecular Projection Explorer"
  doc_url: https://molpx.readthedocs.io/en/latest/
  dev_url: https://github.com/markovmodel/molPX

extra:
  recipe-maintainers:
    - gph82
    - marscher
