travis:
  secure:
    BINSTAR_TOKEN: dFc4fzcagkzx1FbaebggDI8ZNp4ByW6C/GySKmYmt57ZK2gZltQcQZPnjn/pGyYYIc0dvJH3FyQyJ0bgwVI5hxOaJo2r6RTZkSr8PcGdEUfoQnzvVp2qoHHPVcuU8Xl6z8KFTfDqt+89gbmXjBPZ/Rwm/GBuE9RdsF8yUW7fdrOYAUQmZOYXlasTatTpVR5S6OS4ro8uBKT14nviblVOCj+al/k/3vRtQ6IK9Oic0uPVelsc+jBKge06vPmbsgpGTg3WHF16FYOpzOTjdbvMTFW0e4P8Jxb+JYcTfnv0zAN0hibV6QBlqjWMtSecm04FNENmxTnY2Uywhsse+Bp7iI8zJLI36/jHFKuJ2YUt6eR328DEIYnVtXLJPmahBllUfbgxW/h+Z8fK8gF3On2T3qoptJOeDqCvjdrcSdLTY21+ethLdnzFvHZVISAz9aIWQk3i9oVIdD/YtZnKuxvcy02c08s8Dd+Z59MPTM1qr5yo/TQ6HajltPNqI5mzwKiiaGrqRH4NcK4FtFfj29naQqO7MN2O5T5pgP5CWi44WxRW9bcijtRQ6VoNK99VP2Ph6diJRpyVDm+G2rnaeVkdPDfWn8tJ8li2256VBpPJD+u7z5KEC6yAZ1nY++hqWbO0T/ufSUe7IB1457eeZpeFOjfOZJf/MzDWdjJY5VxmnV4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
